spring:
  application:
    name: auto-service-application
  jpa:
    hibernate:
#      ddl-auto: update
      ddl-auto: validate
    properties:
      dialect: org.hibernate.dialect.PostgreSQL15Dialect
  datasource:
    url: jdbc:postgresql://localhost:5432/auto_service_db
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    hikari:
      auto-commit: false
  main:
    allow-circular-references: true