spring:
  application:
    name: auto-service-application
  jpa:
    show-sql: true
    hibernate:
#      ddl-auto: update
      ddl-auto: validate
    properties:
      dialect: org.hibernate.dialect.PostgreSQL15Dialect
  datasource:
    url: jdbc:postgresql://localhost:5432/auto_service_db
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    hikari:
      auto-commit: false
  main:
    allow-circular-references: true
app:
  config:
    image-management:
      get:
        path: /${spring.application.name}/v1/image/get/%s
    non-register:
      stub:
        phone: "без регистрации"
        full-name: "без регистрации"